sudo: required
services:
  - docker

before_install:
  - docker build -t aleksijaakkojuhani/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aleksijaakkojuhani/react-test npm test -- --coverage

after_success:
  - docker build -t aleksijaakkojuhani/multi-client ./client
  - docker build -t aleksijaakkojuhani/multi-nginx ./nginx
  - docker build -t aleksijaakkojuhani/multi-server ./server
  - docker build -t aleksijaakkojuhani/multi-worker ./worker
  # Take these images and push them into docker hub
  # First login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aleksijaakkojuhani/multi-client
  - docker build -t aleksijaakkojuhani/multi-nginx
  - docker build -t aleksijaakkojuhani/multi-server
  - docker build -t aleksijaakkojuhani/multi-worker